# NumPy — Arrays and Numerical Computing

## Introduction

NumPy (Numerical Python) provides the `ndarray` — a fast, memory-efficient array that supports vectorized operations. It is the foundation of virtually every data science library: Pandas, Scikit-learn, TensorFlow, and PyTorch all use NumPy arrays internally.

## Objectives

You will be able to:

* Create NumPy arrays from lists and built-in generators
* Perform vectorized arithmetic and broadcasting
* Index and slice arrays (including 2D)
* Use essential NumPy math functions
* Explain why NumPy is faster than Python lists

---

## Why NumPy?

In [ ]:
import numpy as np
import time

n = 1_000_000

# Python list — element-by-element
py_list = list(range(n))
t0 = time.time()
py_result = [x * 2 for x in py_list]
t1 = time.time()

# NumPy array — vectorized (C-level loop)
np_arr = np.arange(n)
t2 = time.time()
np_result = np_arr * 2
t3 = time.time()

print(f"Python list: {(t1-t0)*1000:.1f}ms")
print(f"NumPy array: {(t3-t2)*1000:.1f}ms")
print(f"Speedup: ~{(t1-t0)/(t3-t2):.0f}x")

NumPy stores data in a **contiguous block of memory** with a fixed dtype — no Python object overhead per element. Operations run in compiled C code, not interpreted Python.

---

## Creating Arrays

In [ ]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype)    # int64 (or int32 on Windows)

b = np.array([1.0, 2.5, 3.7])
print(b, b.dtype)    # float64

# Built-in generators
print(np.zeros(5))                  # [0. 0. 0. 0. 0.]
print(np.ones((2, 3)))              # 2x3 matrix of ones
print(np.full((2, 2), 7))           # 2x2 matrix of 7s
print(np.eye(3))                    # 3x3 identity matrix
print(np.arange(0, 10, 2))         # [0 2 4 6 8]
print(np.linspace(0, 1, 5))        # [0.   0.25 0.5  0.75 1.  ]

# Random arrays
np.random.seed(42)
print(np.random.rand(3, 3))        # uniform [0, 1)
print(np.random.randn(3))          # standard normal
print(np.random.randint(0, 10, 5)) # integers in [0, 10)

---

## Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(f"Shape:   {arr.shape}")    # (2, 3) — 2 rows, 3 columns
print(f"ndim:    {arr.ndim}")     # 2 — number of dimensions
print(f"dtype:   {arr.dtype}")    # int64
print(f"size:    {arr.size}")     # 6 — total elements
print(f"nbytes:  {arr.nbytes}")   # bytes of memory used

---

## Vectorized Operations and Broadcasting

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# Arithmetic — applied element-wise automatically
print(a + 10)     # [11 12 13 14 15]
print(a * 2)      # [ 2  4  6  8 10]
print(a ** 2)     # [ 1  4  9 16 25]
print(a / a)      # [1. 1. 1. 1. 1.]

# Operations between two arrays (element-wise)
b = np.array([10, 20, 30, 40, 50])
print(a + b)      # [11 22 33 44 55]
print(a * b)      # [ 10  40  90 160 250]

# Universal functions (ufuncs)
print(np.sqrt(a))       # [1.    1.414 1.732 2.    2.236]
print(np.exp(a))        # e^1, e^2, ...
print(np.log(a))        # natural log
print(np.abs([-1, -2, 3]))  # [1 2 3]

In [ ]:
# Broadcasting — operating on arrays of different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

# row is broadcast across every row of matrix
print(matrix + row)
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

# Subtract column mean from each column (common normalization)
col_means = matrix.mean(axis=0)  # mean along rows → column means
print(f"Column means: {col_means}")
print(matrix - col_means)

---

## Indexing and Slicing

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Single element: [row, col]
print(arr[1, 2])      # 7

# Rows and columns
print(arr[0])         # first row: [1 2 3 4]
print(arr[:, 1])      # second column: [2 6 10]

# Slices
print(arr[0:2, 1:3])  # rows 0-1, cols 1-2
# [[2 3]
#  [6 7]]

# Boolean indexing — key for filtering
data = np.array([10, 25, 3, 87, 15, 42])
mask = data > 20
print(mask)           # [False  True False  True False  True]
print(data[mask])     # [25 87 42]

# Fancy indexing — select with an integer array
indices = np.array([0, 2, 4])
print(data[indices])  # [10  3 15]

---

## Aggregations and Statistics

In [ ]:
data = np.random.normal(100, 15, size=1000)  # IQ scores

print(f"Mean:     {np.mean(data):.2f}")
print(f"Median:   {np.median(data):.2f}")
print(f"Std Dev:  {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")
print(f"Min:      {np.min(data):.2f}")
print(f"Max:      {np.max(data):.2f}")
print(f"Sum:      {np.sum(data):.2f}")

# Percentiles
print(f"25th pct: {np.percentile(data, 25):.2f}")
print(f"75th pct: {np.percentile(data, 75):.2f}")
print(f"IQR:      {np.percentile(data, 75) - np.percentile(data, 25):.2f}")

In [ ]:
# Axis parameter — aggregate across a dimension
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix.sum())         # 45 — total
print(matrix.sum(axis=0))   # [12 15 18] — sum each column
print(matrix.sum(axis=1))   # [ 6 15 24] — sum each row
print(matrix.mean(axis=0))  # [4. 5. 6.] — column means

---

## Reshaping and Stacking

In [ ]:
# reshape — change shape without changing data
flat = np.arange(12)
grid = flat.reshape(3, 4)
print(grid)
print(grid.reshape(-1))  # -1 means "infer this dimension"

# Transpose
print(grid.T.shape)  # (4, 3)

# Stacking
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack([a, b]))          # [1 2 3 4 5 6]
print(np.vstack([a, b]))          # [[1 2 3] [4 5 6]]
print(np.column_stack([a, b]))    # [[1 4] [2 5] [3 6]]

---

## Practice

In [ ]:
# 1. Create a 5x5 array where element [i,j] = i * j
# Hint: use np.arange and reshape, or broadcasting
result = None
# Expected:
# [[ 0  0  0  0  0]
#  [ 0  1  2  3  4]
#  [ 0  2  4  6  8]
#  [ 0  3  6  9 12]
#  [ 0  4  8 12 16]]
print(result)

In [ ]:
# 2. Given temperature data in Celsius, convert to Fahrenheit: F = C * 9/5 + 32
celsius = np.array([0, 20, 37, 100])
fahrenheit = None
print(fahrenheit)  # Expected: [32.  68.  98.6 212.]

In [ ]:
# 3. From a 4x4 random matrix, extract all elements > 0.5
np.random.seed(0)
mat = np.random.rand(4, 4)
print(mat)
high = None  # boolean indexing
print(f"Elements > 0.5: {high}")

## Summary

| Concept | Key syntax |
|---------|------------|
| Create | `np.array()`, `np.zeros()`, `np.arange()`, `np.linspace()` |
| Shape | `.shape`, `.ndim`, `.size`, `.reshape()` |
| Math | `+`, `*`, `**`, `np.sqrt()`, `np.exp()`, `np.log()` |
| Stats | `np.mean()`, `np.std()`, `np.percentile()`, `.sum(axis=)` |
| Index | `arr[row, col]`, `arr[start:stop]`, `arr[mask]` |
| Combine | `np.hstack()`, `np.vstack()`, `np.column_stack()` |

NumPy is the compute layer. The next notebook introduces **Pandas** — which wraps NumPy arrays in labeled, named structures that are much easier to work with for real-world data.